version: '2.2'
services:
  rabbitmq:
    ports:
      - 5672:5672

  mysql:
    ports:
      - 3306:3306

  redis:
    ports:
    - 6379:6379

  mxshop-config:
    build: mxshop-config
    ports:
      - 8888:8888

  mxshop-eureka:
    build: mxshop-eureka

  mxshop-gateway:
    build: mxshop-gateway

  mxshop-auth:
    build: mxshop-auth
    ports:
      - 5000:5000

  user-service:
    build: user-service
    ports:
      - 8900:8900

  product-service:
    build: product-service
    ports:
      - 8901:8901