version: '2.2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mxshop-config:
    image: chentianzhu/mxshop-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mxshop-eureka:
    image: chentianzhu/mxshop-eureka
    restart: always
    depends_on:
      mxshop-config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mxshop-gateway:
    image: chentianzhu/mxshop-gateway
    restart: always
    depends_on:
      mxshop-config:
        condition: service_healthy
    links:
      - "mxshop-eureka:mxshop-eureka"
      - "mxshop-config:mxshop-config"
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mxshop-auth:
    image: chentianzhu/mxshop-auth
    restart: always
    depends_on:
      mxshop-config:
          condition: service_healthy
    depends_on:
      - mysql
    links:
      - "mxshop-config:mxshop-config"
      - "mxshop-eureka:mxshop-eureka"
      - "mxshop-gateway:mxshop-gateway"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  user-service:
    image: chentianzhu/user-service
    restart: always
    depends_on:
      mxshop-config:
        condition: service_healthy
    depends_on:
      - mysql
    links:
      - "mxshop-config:mxshop-config"
      - "mxshop-eureka:mxshop-eureka"
      - "mxshop-gateway:mxshop-gateway"
      - "mxshop-auth:mxshop-auth"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  product-service:
    image: chentianzhu/product-service
    restart: always
    depends_on:
      mxshop-config:
        condition: service_healthy
    depends_on:
      - mysql
    links:
      - "mxshop-config:mxshop-config"
      - "mxshop-eureka:mxshop-eureka"
      - "mxshop-gateway:mxshop-gateway"
      - "mxshop-auth:mxshop-auth"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  mxshop-monitor:
    image: chentianzhu/mxshop-monitor
    restart: always
    depends_on:
      mxshop-config:
        condition: service_healthy
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  #logspout and elk
  logspout:
    image: gliderlabs/logspout
    command: 'syslog://logstash:5044'
    links:
      - logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  logstash:
    build: logstash
    restart: always
    ports:
      - 5044:5044
    command: logstash -f /config-dir/logstash.conf
    links:
      - elasticsearch

  kibana:
    image: kibana:4.4
    restart: always
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: elasticsearch:2.2
    restart: always
    ports:
      - 9200:9200
    volumes:
      - es_log_data:/var/lib/elasticsearch

volumes:
  db_data:
  es_log_data: