#数据源
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

server:
  context-path: /product
  port: 8901

security:
  oauth2:
    client:
      clientId: product-service
      clientSecret: productservice
      accessTokenUri: http://mxshop-auth:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server
