#数据源
spring.datasource.url: jdbc:mysql://192.168.1.250:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

server:
  context-path: /product
  port: 8901

security:
  oauth2:
    client:
      clientId: product-service
      clientSecret: productservice
      accessTokenUri: http://mxshop-auth:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: springcloud
                password: springcloud
      bindings:
        userChangeInput:
          destination:  userChangeTopic
          content-type: application/json
          binder: rabbitmq