#数据源
spring.datasource.url: jdbc:mysql://mysql:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

#redis
spring.redis.host: redis
spring.redis.port: 6379
spring.redis.password:

server:
  context-path: /product
  port: 8901

security:
  oauth2:
    client:
      clientId: product-service
      clientSecret: productservice
      accessTokenUri: http://mxshop-auth:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.99.100
                port: 5672
                username: guest
                password: guest
      bindings:
        userChangeInput:
          destination:  userChangeTopic
          content-type: application/json
          binder: rabbitmq