#测试配置中心用
example.property: "I AM IN THE DEFAULT"
envProperty: "Test env"

#数据源
spring.datasource.url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

server:
  context-path: /user
  port: 8900

security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: userservice
      accessTokenUri: http://mxshop-auth:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  cloud:
    stream:
      binders:
        rabbitmq:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        userChangeOutput:
          destination:  userChangeTopic
          content-type: application/json
          binder: rabbitmq
